local map = vim.api.nvim_set_keymap
map('n', '<C-a>', 'ggVG', {noremap=true, silent=true})
map('i', '<C-a>', '<Esc>ggVG', {noremap=true, silent=true})
map('v', '<C-c>', 'y', {noremap=true, silent=true})
map('v', '<C-x>', 'd', {noremap=true, silent=true})
map('v', '<C-v>', 'p', {noremap=true, silent=true})
map('i', '<C-z>', '<Esc>ui', {noremap=true, silent=true})
map('i', '<C-y>', '<Esc>:red<Enter>i', {noremap=true, silent=true})
map('i', '<C-s>', '<Esc>:w<Enter>i', {noremap=true})
map('n', '<C-[>', '<Plug>(cokeline-focus-prev)', {noremap=false})
map('n', '<C-]>', '<Plug>(cokeline-focus-next)', {noremap=false})
map('n', '<C-o>', '<CMD>Telescope find_files<CR>', {noremap=true})
map('n', '<C-f>', '<CMD>Telescope live_grep<CR>', {noremap=true})
map('n', '<C-i>', '<CMD>lua require("FTerm").toggle()<CR>', {noremap=true, silent=true})
